msp_user_ambulatorios_homepage:
    path:     /hello/{name}
    defaults: { _controller: MSPUserAmbulatoriosBundle:Default:index }
    
msp_user_ambulatorios_index:
    path:     /user/ambulatorios/index
    defaults: { _controller: MSPUserAmbulatoriosBundle:User:index }
    
msp_user_ambulatorios_edit:
    path:     /user/ambulatorios/edit/{id}
    defaults: { _controller: MSPUserAmbulatoriosBundle:User:edit }  
      
msp_user_ambulatorios_add:
    path:     /user/ambulatorios/add
    defaults: { _controller: MSPUserAmbulatoriosBundle:User:add }
    
msp_user_ambulatorios_save:
    path:     /user/ambulatorios/save{id}
    defaults: { _controller: MSPUserAmbulatoriosBundle:User:save } 
    
msp_user_ambulatorios_signos:
    path:     /user/ambulatorios/signos/{page}
    defaults: { _controller: MSPUserAmbulatoriosBundle:User:signos }    
